name: Docker Image Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t "ghcr.io/crypto-lab-tk/containersentry" .
      
    - uses: actions/checkout@v3
    - name: Login to registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u lanhart --password-stdin
    
    - uses: actions/checkout@v3
    - name: Publish Image
      run: docker push ghcr.io/crypto-lab-tk/containersentry
